const data = {
    // These are indexes to words on rows.
    "columns": ["english", "finnish", "russian"],
    // It's easier on the eyes to write the words in a 1-dimensional array.
    "words": [
        // Numbers:
        "one", "yksi", "один",
        "two", "kaksi", "два",
        "three", "kolme", "три",
        "four", "neljä", "четыре",
        "five", "viisi", "пять",
        "six", "kuusi", "шесть",
        "seven", "seitsemän", "семь",
        "eight", "kahdeksan", "восемь",
        "nine", "yhdeksän", "девять",
        "ten", "kymmenen", "десять",
        // Animals:
        "dog", "koira", "собака",
        "cat", "kissa", "кошка",
        "cow", "lehmä", "корова",
        "pig", "sika", "свинья",
        "mouse", "hiiri", "мышь",
        // Greetings:
        "good morning", "hyvää huomenta", "доброе утро",
        null, "hyvää päivää", "добрый день",
        null, "hyvää iltaa", "добрый вечер",
        null, "hyvää yötä", "спокойной ночи",
        // Misc:
        null, "aamiainen", "завтрак",
        null, "aamulla", "утром",
        null, "aihe", "тема",
        // Time:
        null, "aamu", "утро",
        null, "päivä", "день",
        null, "ilta", "вечер",
        null, "yö", "ночь",
        // TODO: Handle synonyms like these:
        null, "aika", "время",
        null, "aika", "пора",
        null, "aikaisemmin", "раньще",
        null, "aikaisin", "рано",
        null, "aikakauslehti", "журнал",
        null, "aikataulu", "расписание",
        null, "aina", "всегда",
        null, "ainoastaan", "только",
        null, "missä", "где",
        null, "kiitos", "спасибо",
        null, "laukku", "сумка",
        null, "minä en tiedä", "я не знаю",
        null, "lähdetään", "поехали",
    ],
    "gpt": [
        { "RU": "и", "EN-GB": "and", "FI": "ja" },
        { "RU": "в", "EN-GB": "in", "FI": "sisällä" },
        { "RU": "не", "EN-GB": "not", "FI": "ei" },
        { "RU": "он", "EN-GB": "he", "FI": "hän" },
        { "RU": "на", "EN-GB": "on", "FI": "päällä" },
        { "RU": "я", "EN-GB": "I", "FI": "minä" },
        { "RU": "с", "EN-GB": "with", "FI": "kanssa" },
        { "RU": "что", "EN-GB": "what", "FI": "mitä" },
        { "RU": "по", "EN-GB": "by", "FI": "kautta" },
        { "RU": "это", "EN-GB": "this", "FI": "tämä" },
        { "RU": "как", "EN-GB": "how", "FI": "kuinka" },
        { "RU": "мы", "EN-GB": "we", "FI": "me" },
        { "RU": "из", "EN-GB": "from", "FI": "from" },
        { "RU": "за", "EN-GB": "for", "FI": "varten" },
        { "RU": "вы", "EN-GB": "you", "FI": "te", "comment": "formal/plural" },
        { "RU": "так", "EN-GB": "so", "FI": "niin" },
        { "RU": "но", "EN-GB": "but", "FI": "mutta" },
        { "RU": "о", "EN-GB": "about", "FI": "noin" },
        { "RU": "же", "EN-GB": "same", "FI": "sama" },
        { "RU": "ты", "EN-GB": "you", "FI": "sinä", "comment": "informal" },
        { "RU": "мама", "EN-GB": "mom", "FI": "äiti" },
        { "RU": "отец", "EN-GB": "father", "FI": "isä" },
        { "RU": "женщина", "EN-GB": "woman", "FI": "nainen" },
        { "RU": "мужчина", "EN-GB": "man", "FI": "mies" },
        { "RU": "друг", "EN-GB": "friend", "FI": "ystävä" },
        { "RU": "брат", "EN-GB": "brother", "FI": "veli" },
        { "RU": "сестра", "EN-GB": "sister", "FI": "sisar" },
        { "RU": "город", "EN-GB": "city", "FI": "kaupunki" },
        { "RU": "лес", "EN-GB": "forest", "FI": "metsä" },
        { "RU": "гора", "EN-GB": "mountain", "FI": "vuori" },
        { "RU": "река", "EN-GB": "river", "FI": "joki" },
        { "RU": "море", "EN-GB": "sea", "FI": "meri" },
        { "RU": "небо", "EN-GB": "sky", "FI": "taivas" },
        { "RU": "солнце", "EN-GB": "sun", "FI": "aurinko" },
        { "RU": "звезда", "EN-GB": "star", "FI": "tähti" },
        { "RU": "месяц", "EN-GB": "month", "FI": "kuukausi" },
        { "RU": "деньги", "EN-GB": "money", "FI": "raha" },
        { "RU": "работа", "EN-GB": "work", "FI": "työ" },
        { "RU": "школа", "EN-GB": "school", "FI": "koulu" },
        { "RU": "учитель", "EN-GB": "teacher", "FI": "opettaja" },
        { "RU": "студент", "EN-GB": "student", "FI": "opiskelija" }
    ]
};
